### ISSUE TITLE
Only delete files

### ISSUE THREAD

**Issue by mmunchandersen** [merken/Prise.VisualStudioExtensions#3]
Hi Maarten.
Great little extension (emtpy-directory-extension).
It would be even greater if it could also "empty only files in a directory recursively, and keep all folders" :-)

**Comment by mmunchandersen** [comment]
Thanks Maarten. Works like a charm, even if the menu item text is the longest ever ;-)

**Comment by merken** [comment]
You're welcome!
Regarding the menu item text, I did not want to disappoint 😃
